pipeline {
    agent any

    environment {
        GIT_COMMIT = sh(returnStdout: true, script: 'git ls-remote https://gitlab.rero.ch/rero21/reroils-record-editor.git refs/heads/master | cut -c1-10 ').trim()
    }

    stages {
        stage('Get Dockerfile') {
            steps {
                sh "curl -O https://gitlab.rero.ch/rero21/reroils-record-editor/raw/master/development/Dockerfile"
                sh "curl -O https://gitlab.rero.ch/rero21/reroils-record-editor/raw/master/development/build_app.sh"
            }
        }
       
        stage('Build Test Docker Image') {
                steps {
                    println('Building GIT_COMMIT:'+GIT_COMMIT+ ' ...')
                    script {
                        app_dev = docker.build('rero/reroils-record-editor:test', '--build-arg GIT_COMMIT=$GIT_COMMIT --rm  -f Dockerfile .')
                    }
                }
        }
        stage('Run Test') {
            steps {
                script {
                   sh "docker run --rm rero/reroils-record-editor:test"
                }
            }
        }

        stage('Cleaning') {
                steps {
                    echo 'Cleaning....'
                    script {
                        sh "docker rmi rero/reroils-record-editor:test"
                    }
                }
         }
    }
    post { 
        failure { 
            echo 'failure: dying now'
            mail (to: 'software@rero.ch',
                  subject: "[Jenkins] Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) has failed",
                  body: "Please go to ${env.BUILD_URL}.");

        }
    }
}
